# Generated by Django 4.2 on 2023-09-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appInmoSoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInteresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliNombre', models.CharField(db_comment='Nombre del cliente', max_length=50)),
                ('cliApellido', models.CharField(db_comment='Apellido del cliente', max_length=50)),
                ('cliTelefono', models.CharField(db_comment='Telefono del cliente', max_length=50)),
                ('cliCorreo', models.CharField(db_comment='Correo del cliente', max_length=50)),
                ('cliCedula', models.CharField(db_comment='cedula del cliente', max_length=50)),
                ('clifechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('clifechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('cliProyecto', models.ForeignKey(db_comment='Proyecto interesado del cliente', on_delete=django.db.models.deletion.PROTECT, to='appInmoSoft.proyecto')),
            ],
        ),
    ]
