# Generated by Django 4.2.1 on 2023-07-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appInmoSoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='inmValorInmueble',
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='apaNumeroInmueble',
            field=models.IntegerField(db_comment='Numero de inmuebles por torre'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='apaNumeroTorre',
            field=models.IntegerField(db_comment='Numero de Torres'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='inmApartamento',
            field=models.ForeignKey(db_comment='hace refencia al tipo de inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='appInmoSoft.apartamento'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='inmCasa',
            field=models.ForeignKey(db_comment='hace referencia al tipo de inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='appInmoSoft.casas'),
        ),
    ]
